# .github/workflows/demo.yml

name: create :NEXT docker & push image on pull request to dev

on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
   pull_request:
    branches: [ "next" ]

jobs:
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sergion14/expressjs-template:next

  koyeb-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"
      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          service-env: "PORT=3000"
          service-ports: "3000:http"
          service-routes: "/:3000"
          app-name: "expressjs-template-next"
          service-name: "expressjs-template-next"
          service-type: "web"
          service-regions: "fra"

