name: create :LATEST docker & push image on pull request

on:
    pull_request:
        branches: [ "next" ]

jobs:
    koyeb-deploy:
        runs-on: ubuntu-latest
        environment: dev
        concurrency: 
            group: "${{ github.ref_name }}"
            cancel-in-progress: true
        steps:
            # -
            #     name: Create application secret
            #     uses: koyeb/action-git-deploy/secret@v1
            #     with:
            #         secret-name: BREVO_API_KEY
            #         secret-value: "${{ secrets.BREVO_API_KEY }}" 

            - 
                name: Install and configure the Koyeb CLI
                uses: koyeb-community/koyeb-actions@v2
                with:
                    api_token: "${{ secrets.KOYEB_API_TOKEN }}"
            -
                name: Use repository secret
                run: echo "Using ${{ secrets.KOYEB_API_TOKEN }} and ${{ secrets.DOCKER_PRIVATE_REGISTRY_SECRET }}" 
            -
                name: Build and deploy the application to Koyeb
                uses: koyeb/action-git-deploy@v1
                with:
                    service-env: "PORT=3000"
                    service-ports: "3000:http"
                    service-routes: "/:3000"
                    service-regions: "fra"
                    docker: "sergion14/expressjs-template:latest"
                    docker-private-registry-secret: "${{ secrets.DOCKER_PRIVATE_REGISTRY_SECRET }}"
                    docker-command: "CMD [\"./startLocal.sh\"]"
